name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'    # Triggers when pushing tags like v1.0.0

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the module folder
        run: |
          zip -r GitHubHelperTools.zip Public Private GitHubHelperTools.psm1 GitHubHelperTools.psd1 LICENSE README.md .gitignore

      - name: Create GitHub Release with Asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: GitHubHelperTools.zip